# Вычисления с помощью Numpy

## Task 1

In [96]:
import numpy as np

In [97]:
a = np.array([[1, 6], 
              [2, 8], 
              [3, 11],
              [3, 10],
              [1, 7]])

In [98]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [99]:
a_mean = a.mean(axis=0)
a_mean

array([2. , 8.4])

## Task 2

In [100]:
a_centered = a - a_mean
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Task 3

In [101]:
b = a_centered.sum()
c = a_centered[0: , 1:]
b, c

(-1.7763568394002505e-15,
 array([[-2.4],
        [-0.4],
        [ 2.6],
        [ 1.6],
        [-1.4]]))

In [102]:
a_centered_sp = np.dot(b, c)
a_centered_sp

array([[ 4.26325641e-15],
       [ 7.10542736e-16],
       [-4.61852778e-15],
       [-2.84217094e-15],
       [ 2.48689958e-15]])

In [103]:
rows, columns = a.shape
d = a_centered_sp / (rows - 1)
d

array([[ 1.06581410e-15],
       [ 1.77635684e-16],
       [-1.15463195e-15],
       [-7.10542736e-16],
       [ 6.21724894e-16]])

## Task 4

In [104]:
? np.cov

In [105]:
cov = np.cov(a.T)
cov

array([[1. , 2. ],
       [2. , 4.3]])

# Работа с данными в Pandas

## Task 1

In [106]:
import pandas as pd

In [107]:
authors = pd.DataFrame({
    'author_id': [1, 2, 3],
    'author_name': ['Тургенев', 'Чехов', 'Островский'],
})

authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [108]:
'Тургенев', 'Чехов', 'Островский'

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

## Task 2

In [109]:
merged_df = pd.merge(authors, books, on='author_id', how='inner')

merged_df

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

## Task 3

In [111]:
authors_price = merged_df.nlargest(5, "price")

authors_price

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

## Task 4

In [128]:
authors_price["max_price"] = authors_price["price"].max()
authors_price["min_price"] = authors_price["price"].min()
authors_price["mean_price"] = authors_price["price"].mean()
authors_price

author_id author_name         book_title  price  min  max_price  min_price  \
3          2       Чехов   Толстый и тонкий    500  500        500        350   
0          1    Тургенев        Отцы и дети    450  500        500        350   
4          2       Чехов    Дама с собачкой    450  500        500        350   
5          3  Островский              Гроза    370  500        500        350   
2          1    Тургенев  Дворянское гнездо    350  500        500        350   

   mean_price  
3       424.0  
0       424.0  
4       424.0  
5       424.0  
2       424.0

## Task 5

In [130]:
merged_df.loc[merged_df["book_title"].notnull(), "cover"] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

merged_df

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая